export { EmailIcon } from './email-icon';
export { PasswordIcon } from './password-icon';
export { OpenEyeIcon } from './eye-icon';
export { CloseEyeIcon } from './close-icon';
export { ChevronUpIcon } from './chevron-up-icon';
export { ChevronDownIcon } from './chevron-down-icon';
export { FilterListIcon } from './filter-list-icon';
export { PlusIcon } from './plus-icon';
export { SearchIcon } from './search-icon';
export { DeleteIcon } from './delete-icon';
export { DotIcon } from './dot-icon';
export { ActiveIcon } from './active-icon';
export { DesactiveIcon } from './desactive-icon';
export { EditIcon } from './edit-icon';
export { SpecialtyIcon } from './specialty-icon';
export { UnitIcon } from './unit-icon';
export { AbrevationIcon } from './abrevation-icon';
export { ParagraphIcon } from './paragraph-icon';
export { VaccinesIcon } from './vaccines-icon';
export { CompaniesIcon } from './companies-icon';
export { TagsIcon } from './tags-icon';
export { RolesIcon } from './roles-icons';
export { PrioridadIcon } from './prioridad-icon';
export { BodegaIcon } from './bodega-icon';
export { ProductosIcon } from './productos-icon';
export { ClientesIcon } from './clientes-icon';
export { TicketIcon } from './ticket-icon'
export { PhoneIcon } from './phone-icon'
export { WhatsappIcon } from './whatsapp-icon'